/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConfidentialitateRouteImport } from './routes/confidentialitate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DespreRouteImport } from './routes/despre'
import { Route as IntrebariFrecventeRouteImport } from './routes/intrebari-frecvente'
import { Route as NoutatiRouteImport } from './routes/noutati'
import { Route as PreturiRouteImport } from './routes/preturi'
import { Route as ProcesRouteImport } from './routes/proces'
import { Route as ServiciiRouteImport } from './routes/servicii'
import { Route as TermeniRouteImport } from './routes/termeni'
import { Route as TestimonialeRouteImport } from './routes/testimoniale'
import { Route as ZonaDeAcoperireRouteImport } from './routes/zona-de-acoperire'
import { Route as AuthenticatedAdministrareRouteImport } from './routes/_authenticated/administrare'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedSolicitariIndexRouteImport } from './routes/_authenticated/solicitari.index'
import { Route as AuthenticatedSolicitariIdRouteImport } from './routes/_authenticated/solicitari.$id'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialitateRoute = ConfidentialitateRouteImport.update({
  id: '/confidentialitate',
  path: '/confidentialitate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DespreRoute = DespreRouteImport.update({
  id: '/despre',
  path: '/despre',
  getParentRoute: () => rootRouteImport,
} as any)
const IntrebariFrecventeRoute = IntrebariFrecventeRouteImport.update({
  id: '/intrebari-frecvente',
  path: '/intrebari-frecvente',
  getParentRoute: () => rootRouteImport,
} as any)
const NoutatiRoute = NoutatiRouteImport.update({
  id: '/noutati',
  path: '/noutati',
  getParentRoute: () => rootRouteImport,
} as any)
const PreturiRoute = PreturiRouteImport.update({
  id: '/preturi',
  path: '/preturi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesRoute = ProcesRouteImport.update({
  id: '/proces',
  path: '/proces',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciiRoute = ServiciiRouteImport.update({
  id: '/servicii',
  path: '/servicii',
  getParentRoute: () => rootRouteImport,
} as any)
const TermeniRoute = TermeniRouteImport.update({
  id: '/termeni',
  path: '/termeni',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialeRoute = TestimonialeRouteImport.update({
  id: '/testimoniale',
  path: '/testimoniale',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonaDeAcoperireRoute = ZonaDeAcoperireRouteImport.update({
  id: '/zona-de-acoperire',
  path: '/zona-de-acoperire',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministrareRoute =
  AuthenticatedAdministrareRouteImport.update({
    id: '/administrare',
    path: '/administrare',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSolicitariIndexRoute =
  AuthenticatedSolicitariIndexRouteImport.update({
    id: '/solicitari/',
    path: '/solicitari/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSolicitariIdRoute =
  AuthenticatedSolicitariIdRouteImport.update({
    id: '/solicitari/$id',
    path: '/solicitari/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/noutati': typeof NoutatiRoute
  '/preturi': typeof PreturiRoute
  '/proces': typeof ProcesRoute
  '/servicii': typeof ServiciiRoute
  '/termeni': typeof TermeniRoute
  '/testimoniale': typeof TestimonialeRoute
  '/zona-de-acoperire': typeof ZonaDeAcoperireRoute
  '/administrare': typeof AuthenticatedAdministrareRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/solicitari/$id': typeof AuthenticatedSolicitariIdRoute
  '/solicitari/': typeof AuthenticatedSolicitariIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/noutati': typeof NoutatiRoute
  '/preturi': typeof PreturiRoute
  '/proces': typeof ProcesRoute
  '/servicii': typeof ServiciiRoute
  '/termeni': typeof TermeniRoute
  '/testimoniale': typeof TestimonialeRoute
  '/zona-de-acoperire': typeof ZonaDeAcoperireRoute
  '/administrare': typeof AuthenticatedAdministrareRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/solicitari/$id': typeof AuthenticatedSolicitariIdRoute
  '/solicitari': typeof AuthenticatedSolicitariIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/confidentialitate': typeof ConfidentialitateRoute
  '/contact': typeof ContactRoute
  '/despre': typeof DespreRoute
  '/intrebari-frecvente': typeof IntrebariFrecventeRoute
  '/noutati': typeof NoutatiRoute
  '/preturi': typeof PreturiRoute
  '/proces': typeof ProcesRoute
  '/servicii': typeof ServiciiRoute
  '/termeni': typeof TermeniRoute
  '/testimoniale': typeof TestimonialeRoute
  '/zona-de-acoperire': typeof ZonaDeAcoperireRoute
  '/_authenticated/administrare': typeof AuthenticatedAdministrareRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/solicitari/$id': typeof AuthenticatedSolicitariIdRoute
  '/_authenticated/solicitari/': typeof AuthenticatedSolicitariIndexRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/confidentialitate'
    | '/contact'
    | '/despre'
    | '/intrebari-frecvente'
    | '/noutati'
    | '/preturi'
    | '/proces'
    | '/servicii'
    | '/termeni'
    | '/testimoniale'
    | '/zona-de-acoperire'
    | '/administrare'
    | '/blog/$slug'
    | '/blog/'
    | '/solicitari/$id'
    | '/solicitari/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/confidentialitate'
    | '/contact'
    | '/despre'
    | '/intrebari-frecvente'
    | '/noutati'
    | '/preturi'
    | '/proces'
    | '/servicii'
    | '/termeni'
    | '/testimoniale'
    | '/zona-de-acoperire'
    | '/administrare'
    | '/blog/$slug'
    | '/blog'
    | '/solicitari/$id'
    | '/solicitari'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/confidentialitate'
    | '/contact'
    | '/despre'
    | '/intrebari-frecvente'
    | '/noutati'
    | '/preturi'
    | '/proces'
    | '/servicii'
    | '/termeni'
    | '/testimoniale'
    | '/zona-de-acoperire'
    | '/_authenticated/administrare'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/solicitari/$id'
    | '/_authenticated/solicitari/'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConfidentialitateRoute: typeof ConfidentialitateRoute
  ContactRoute: typeof ContactRoute
  DespreRoute: typeof DespreRoute
  IntrebariFrecventeRoute: typeof IntrebariFrecventeRoute
  NoutatiRoute: typeof NoutatiRoute
  PreturiRoute: typeof PreturiRoute
  ProcesRoute: typeof ProcesRoute
  ServiciiRoute: typeof ServiciiRoute
  TermeniRoute: typeof TermeniRoute
  TestimonialeRoute: typeof TestimonialeRoute
  ZonaDeAcoperireRoute: typeof ZonaDeAcoperireRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialitate': {
      id: '/confidentialitate'
      path: '/confidentialitate'
      fullPath: '/confidentialitate'
      preLoaderRoute: typeof ConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despre': {
      id: '/despre'
      path: '/despre'
      fullPath: '/despre'
      preLoaderRoute: typeof DespreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intrebari-frecvente': {
      id: '/intrebari-frecvente'
      path: '/intrebari-frecvente'
      fullPath: '/intrebari-frecvente'
      preLoaderRoute: typeof IntrebariFrecventeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noutati': {
      id: '/noutati'
      path: '/noutati'
      fullPath: '/noutati'
      preLoaderRoute: typeof NoutatiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preturi': {
      id: '/preturi'
      path: '/preturi'
      fullPath: '/preturi'
      preLoaderRoute: typeof PreturiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proces': {
      id: '/proces'
      path: '/proces'
      fullPath: '/proces'
      preLoaderRoute: typeof ProcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicii': {
      id: '/servicii'
      path: '/servicii'
      fullPath: '/servicii'
      preLoaderRoute: typeof ServiciiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni': {
      id: '/termeni'
      path: '/termeni'
      fullPath: '/termeni'
      preLoaderRoute: typeof TermeniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimoniale': {
      id: '/testimoniale'
      path: '/testimoniale'
      fullPath: '/testimoniale'
      preLoaderRoute: typeof TestimonialeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zona-de-acoperire': {
      id: '/zona-de-acoperire'
      path: '/zona-de-acoperire'
      fullPath: '/zona-de-acoperire'
      preLoaderRoute: typeof ZonaDeAcoperireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administrare': {
      id: '/_authenticated/administrare'
      path: '/administrare'
      fullPath: '/administrare'
      preLoaderRoute: typeof AuthenticatedAdministrareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/solicitari/': {
      id: '/_authenticated/solicitari/'
      path: '/solicitari'
      fullPath: '/solicitari/'
      preLoaderRoute: typeof AuthenticatedSolicitariIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/solicitari/$id': {
      id: '/_authenticated/solicitari/$id'
      path: '/solicitari/$id'
      fullPath: '/solicitari/$id'
      preLoaderRoute: typeof AuthenticatedSolicitariIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdministrareRoute: typeof AuthenticatedAdministrareRoute
  AuthenticatedSolicitariIdRoute: typeof AuthenticatedSolicitariIdRoute
  AuthenticatedSolicitariIndexRoute: typeof AuthenticatedSolicitariIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdministrareRoute: AuthenticatedAdministrareRoute,
  AuthenticatedSolicitariIdRoute: AuthenticatedSolicitariIdRoute,
  AuthenticatedSolicitariIndexRoute: AuthenticatedSolicitariIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConfidentialitateRoute: ConfidentialitateRoute,
  ContactRoute: ContactRoute,
  DespreRoute: DespreRoute,
  IntrebariFrecventeRoute: IntrebariFrecventeRoute,
  NoutatiRoute: NoutatiRoute,
  PreturiRoute: PreturiRoute,
  ProcesRoute: ProcesRoute,
  ServiciiRoute: ServiciiRoute,
  TermeniRoute: TermeniRoute,
  TestimonialeRoute: TestimonialeRoute,
  ZonaDeAcoperireRoute: ZonaDeAcoperireRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
